### ISSUE TITLE
Update pagination to work with search items and filters

### ISSUE THREAD

**Issue by willywos** [willywos/jobbyjobjob#16]
When a user clicks on a filter or enters a search term the pagination does not update. The links for the pagination do not retain the search results and goes back. 

**To Reproduce**
1. Go to home page
2. Click on 'Rails'
3. Notice pagination still is paginating on results from the home screen and does not update.
4. Scroll down to 'the pagination links 1.2.3.4'
5. Click on the number 2
6. The link removes the filter or search item and you are back to seeing all jobs. 

**Expected behavior**
When a user searches or clicks on a filter the pagination should update to reflect how many pages/posts there are based on the users search result or filter.

**Screenshots**
![image](https://user-images.githubusercontent.com/101503/46518271-fb9e9d00-c838-11e8-93f4-f7dc8c20699a.png)

**Comment by OvidiuToma** [comment]
Created pr: https://github.com/willywos/jobbyjobjob/pull/19

**Comment by willywos** [comment]
Thank you it works great!
