### ISSUE TITLE
Update about page and readme to include people who have contributed

### ISSUE THREAD

**Issue by willywos** [willywos/jobbyjobjob#17]
I thought it would be good to see if we could list everyone who has helped contribute to the site and show their avatar and name. 

Something likes this:

![image](https://user-images.githubusercontent.com/101503/46518444-cc3c6000-c839-11e8-95d4-e1dd10328580.png)

Would be great to see it on the readme and on the about page for the site.

**Comment by jawwwr** [comment]
I'll take this one.

**Comment by inqii** [comment]
Hey @willywos! Im participating in the Hacktoberfest and will do this today! 
Best,
Daniel

**Comment by willywos** [comment]
Welp I merged it thinking that it would render in github differently then what it was showing me in the pull request but it looks a little broken. Could you take a look at the project readme again and submit another pull request? Thanks @inqii for working on this.

**Comment by inqii** [comment]
Oh snap! I coded it using hackmd.io and there it looked fine. I fixed it now, the problem was that I changed the layout to three columns but used a row break with five columns. Should look fine now!

**Comment by willywos** [comment]
Yay looks good!
