### ISSUE TITLE
Fix company logos so they don't look skewed.

### ISSUE THREAD

**Issue by willywos** [willywos/jobbyjobjob#25]
Some of the company logos that show on the site do not look good and appear to be skewed.  

![screenshot 2018-10-09 09 42 12](https://user-images.githubusercontent.com/101503/46677164-b0251f80-cba7-11e8-95d2-44a67fe2d80b.png)

**To Reproduce**
1. Go to main website
2. Click on 'rails' on the sidebar
3. Scroll down to 'Senior Rails engineer' (attached screenshot)
4. See image of the logo is skewed.

**Expected behavior**
The image should show up and not look skewed and look like the other images that show up correctly.

**Comment by edmistond** [comment]
I took a crack at this one. Hope you're good with the CSS fix - as noted in the commit message, a potential issue would be if the logo image is, for some reason, really tall. It's uncommon but would blow up the layout in that case.

I am by no means a CSS expert so there may be a simpler way to accomplish this. :) Happy Hacktoberfest, and thanks for making an awesome little tool! :)

**Comment by willywos** [comment]
@edmistond Yeah this looks much better now. Thank You for working on this issue. I'm not a CSS expert either haha but I went through a bunch of postings and didn't see anything really that problems. Happy Hacktoberfest!
