### ISSUE TITLE
 Provide a company page

### ISSUE THREAD

**Issue by willywos** [willywos/jobbyjobjob#28]
Provide a company page for users to be able to view postings by a company. 

When a user views a job posting or views the posting on the index, search or job posting view the company will have a link to a new company page. 

![image](https://user-images.githubusercontent.com/101503/46912728-5cb62700-cf43-11e8-9ed4-16c80c0a58b7.png)

![image](https://user-images.githubusercontent.com/101503/46912740-a868d080-cf43-11e8-9e20-0886f22e1d98.png)

The company page should include:
- The name of the company
- List any job postings by that company (like it does on the index) 
- There should include a back button in the top right. 
- The results should also be paginated 
- The postings should be available in rss and json like on the index.

![image](https://user-images.githubusercontent.com/101503/46912805-54f78200-cf45-11e8-8cd5-21d30e5ad3f5.png)

Additional Features
- Integrate with Glassdoor (if possible) to provide feedback about the company.
- Provide a link to the company website (this may not be possible because the postings don't always include a link to the company site)
- Add filter for the postings

**Comment by willywos** [comment]
This might be a little large of a feature for someone else to work on. I can provide clarifications if needed and answer any questions if someone does pick it up.

**Comment by jereinhardt** [comment]
I'd be able to take a swing at this.

**Comment by willywos** [comment]
Thanks @jereinhardt that would be great!
