### ISSUE TITLE
Add ability to remove an item from the view history.

### ISSUE THREAD

**Issue by willywos** [willywos/jobbyjobjob#29]
On the right side of the postings page it lists the items that you previously viewed. It might be nice to add a delete action because the list can get rather long. It might also be nice to only show 10 of last viewed items.

![image](https://user-images.githubusercontent.com/101503/46913222-b40dc480-cf4e-11e8-8a54-02703a527864.png)

**Comment by andersonfernandes** [comment]
Hi @willywos I would like to work on this issue.

**Comment by willywos** [comment]
Yeah go for it!

**Comment by andersonfernandes** [comment]
Created pr #30 with the implementation
