### ISSUE TITLE
Add ability for users to update their profile and password

### ISSUE THREAD

**Issue by willywos** [willywos/jobbyjobjob#35]
Currently on the site there is no way for a user to update their password. When a user logs into their account they should be able to go to settings and update password.

Settings should also include these new fields:

- First Name
- Last Name
- Address
- City
- State
- Zip
- Phone Number
- Profile Picture (this would connect to s3 with paperclip)
- Website

These fields should be integrated into the resume builder and auto-populated when creating a new resume. Information will not be available to other users or users who are not logged in.

**Comment by monsieurkayode** [comment]
Hi @willywos, great site you have here. I will like to submit a pull request for this feature.

**Comment by willywos** [comment]
Sure if you wanna pick it up that would be great. Thank You!
